<?php

    $cities = [
        ['en_name' => 'Riyadh', 'name' => 'الرياض' ],
        ['en_name' => 'Ad Diriyah', 'name' => 'الدرعية' ],
        ['en_name' => 'Al-Kharj', 'name' => 'الخرج' ],
        ['en_name' => 'Dawadmi', 'name' => 'الدودامي' ],
        ['en_name' => 'Al Majma`ah', 'name' => 'المجمعة' ],
        ['en_name' => 'Al-Gwei\'iyyah', 'name' => 'القويعية' ],
        ['en_name' => 'Layla', 'name' => 'الافلاج' ],
        ['en_name' => 'Wadi Al-Dawasir', 'name' => 'وادي الدواسر' ],
        ['en_name' => 'Zulfi', 'name' => 'الزلفي' ],
        ['en_name' => 'Shaqraa', 'name' => 'شقراء' ],
        ['en_name' => 'Howtat Bani Tamim', 'name' => 'حوصة بني تميم' ],
        ['en_name' => 'Afif', 'name' => 'عفيف' ],
        ['en_name' => 'Al Ghat', 'name' => 'الغاط' ],
        ['en_name' => 'As Sulayyil', 'name' => 'السليل' ],
        ['en_name' => 'Dhurma', 'name' => 'ضرما' ],
        ['en_name' => 'Al-Muzahmiya', 'name' => 'المزاحمية' ],
        ['en_name' => 'Rumah', 'name' => 'رماح' ],
        ['en_name' => 'Thadiq', 'name' => 'ثادق' ],
        ['en_name' => 'Huraymila', 'name' => 'حريملاء' ],
        ['en_name' => 'Al Hariq', 'name' => 'الحريق' ],
        ['en_name' => 'Murat', 'name' => 'مرات' ],
        ['en_name' => 'Ar Rayn', 'name' => 'الرين' ],
        ['en_name' => 'Ad-Dilam', 'name' => 'الدلم' ],
        ['en_name' => 'Mecca', 'name' => 'العاصمة المقدسة'],
        ['en_name' => 'Jeddah', 'name' => 'جدة' ],
        ['en_name' => 'Taif', 'name' => 'الطائف' ],
        ['en_name' => 'Al Qunfudhah', 'name' => 'القنفذة' ],
        ['en_name' => 'Al Lith', 'name' => 'الليث' ],
        ['en_name' => 'Khulais', 'name' => 'خليص' ],
        ['en_name' => 'Al Khurma', 'name' => 'الخرمة' ],
        ['en_name' => 'Ranyah', 'name' => 'رنية' ],
        ['en_name' => 'Turbah', 'name' => 'تربة' ],
        ['en_name' => 'Al-Jumum', 'name' => 'الجموم' ],
        ['en_name' => 'Al Kamil', 'name' => 'الكامل' ],
        ['en_name' => 'Al Muwayh', 'name' => 'المويه' ],
        ['en_name' => 'Maysaan', 'name' => 'ميسان' ],
        ['en_name' => 'Adham', 'name' => 'أضم' ],
        ['en_name' => 'Al-Ardiyat', 'name' => 'العرضيات' ],
        ['en_name' => 'Bahrah', 'name' => 'بحرة' ],
        ['en_name' => 'Medina', 'name' => 'المدينة المنورة'],
        ['en_name' => 'Yanbu', 'name' => 'ينبع' ],
        ['en_name' => 'AlUla', 'name' => 'العلا' ],
        ['en_name' => 'Mahd adh Dhahab', 'name' => 'المهد' ],
        ['en_name' => 'Al Hinakiyah', 'name' => 'الحناكية' ],
        ['en_name' => 'Badr', 'name' => 'بدر' ],
        ['en_name' => 'Khaybar', 'name' => 'خيبر' ],
        ['en_name' => 'Al Ais', 'name' => 'العيص' ],
        ['en_name' => 'Wadi Al Fora\'a', 'name' => 'وادي الفرع' ],
        ['en_name' => 'Buraydah', 'name' => 'بريدة' ],
        ['en_name' => 'Unaizah', 'name' => 'عنيزة' ],
        ['en_name' => 'Ar Rass', 'name' => 'الرس' ],
        ['en_name' => 'Al Mithnab', 'name' => 'المذنب' ],
        ['en_name' => 'Al Bukayriyah', 'name' => 'البكيرية' ],
        ['en_name' => 'Al Badayea', 'name' => 'البدائع' ],
        ['en_name' => 'Asyah', 'name' => 'الأسياح' ],
        ['en_name' => 'An Nabhaniyah', 'name' => 'النبهانية' ],
        ['en_name' => 'Al Shimasiyah', 'name' => 'الشماسية' ],
        ['en_name' => 'Uyun Al Jawa', 'name' => 'عيون الجواء' ],
        ['en_name' => 'Riyadh Al Khabra', 'name' => 'رياض الخبراء' ],
        ['en_name' => 'Uglat Asugour', 'name' => 'عقلة الصقور' ],
        ['en_name' => 'Dariyah', 'name' => 'ضرية' ],
        ['en_name' => 'Dammam', 'name' => 'الدمام' ],
        ['en_name' => 'Al-Ahsa', 'name' => 'الأحساء' ],
        ['en_name' => 'Hafar Al Batin', 'name' => 'حفر الباطن' ],
        ['en_name' => 'Al Jubail', 'name' => 'الجبيل' ],
        ['en_name' => 'Al Qatif', 'name' => 'القطيف' ],
        ['en_name' => 'El Khabar', 'name' => 'الخبر' ],
        ['en_name' => 'Khafji', 'name' => 'الخفجي' ],
        ['en_name' => 'Ras Tanura', 'name' => 'رأس تنورة' ],
        ['en_name' => 'Buqayq', 'name' => 'بقيق' ],
        ['en_name' => 'Nairyah', 'name' => 'النعيرية' ],
        ['en_name' => 'Qaryat Al Ulya', 'name' => 'قرية العليا' ],
        ['en_name' => 'Inland Sea', 'name' => 'العديد' ],
        ['en_name' => 'Abha', 'name' => 'أبها' ],
        ['en_name' => 'Khamis Mushait', 'name' => 'خميس مشيط' ],
        ['en_name' => 'Bisha', 'name' => 'بيشة' ],
        ['en_name' => 'Al Namas', 'name' => 'النماص' ],
        ['en_name' => 'Muhayil', 'name' => 'محايل عسير' ],
        ['en_name' => 'Dhahran Al Janub', 'name' => 'ظهران الجنوب' ],
        ['en_name' => 'تثليث', 'name' => 'تثليث' ],
        ['en_name' => 'Sarat Abidah', 'name' => 'سراة عبيدة' ],
        ['en_name' => 'Rijal Almaa', 'name' => 'رجال ألمع' ],
        ['en_name' => 'Balqarn', 'name' => 'بلقرن' ],
        ['en_name' => 'Ahad Rafidah', 'name' => 'أحد رفيدة' ],
        ['en_name' => 'Al Majaridah', 'name' => 'المجاردة' ],
        ['en_name' => 'Al Birk', 'name' => 'البرك' ],
        ['en_name' => 'Bariq', 'name' => 'بارق' ],
        ['en_name' => 'Tanomah', 'name' => 'تنومة' ],
        ['en_name' => 'Tereeb', 'name' => 'طريب' ],
        ['en_name' => 'Al Harajah', 'name' => 'الحرجة' ],
        ['en_name' => 'Tabuk', 'name' => 'تبوك' ],
        ['en_name' => 'Al Wajh', 'name' => 'الوجه' ],
        ['en_name' => 'Duba', 'name' => 'ضبا' ],
        ['en_name' => 'Tayma', 'name' => 'تيماء' ],
        ['en_name' => 'Umluj', 'name' => 'أملج' ],
        ['en_name' => 'Haql', 'name' => 'حقل' ],
        ['en_name' => 'Al-Bad', 'name' => 'البدع' ],
        ['en_name' => 'Hail', 'name' => 'حائل' ],
        ['en_name' => 'Baqaa', 'name' => 'بقعاء' ],
        ['en_name' => 'Al Ghazalah', 'name' => 'الغزالة' ],
        ['en_name' => 'Ash Shinan', 'name' => 'الشنان' ],
        ['en_name' => 'Al Hait', 'name' => 'الحائط' ],
        ['en_name' => 'Al Sulaimi', 'name' => 'السليمي' ],
        ['en_name' => 'Ash Shamli', 'name' => 'الشملي' ],
        ['en_name' => 'Mawqaq', 'name' => 'موقق' ],
        ['en_name' => 'Sumaira\'a', 'name' => 'سميراء' ],
        ['en_name' => 'Arʿar', 'name' => 'عرعر' ],
        ['en_name' => 'Rafha', 'name' => 'رفحاء' ],
        ['en_name' => 'Turaif', 'name' => 'طريف' ],
        ['en_name' => 'Al Uwayqilah', 'name' => 'العويقيلة' ],
        ['en_name' => 'Jazan', 'name' => 'جازان' ],
        ['en_name' => 'Sabya', 'name' => 'صبيا' ],
        ['en_name' => 'Abu Arish', 'name' => 'أبو عريش' ],
        ['en_name' => 'Samtah', 'name' => 'صامطة' ],
        ['en_name' => 'Baish', 'name' => 'بيش' ],
        ['en_name' => 'Ad Darb', 'name' => 'الدرب' ],
        ['en_name' => 'Al Harth', 'name' => 'الحرث' ],
        ['en_name' => 'Damad', 'name' => 'ضمد' ],
        ['en_name' => 'Al Reeth', 'name' => 'الريث' ],
        ['en_name' => 'Farasan', 'name' => 'فرسان' ],
        ['en_name' => 'Addayer', 'name' => 'الدائر' ],
        ['en_name' => 'Al Aridhah', 'name' => 'العارضة' ],
        ['en_name' => 'Ahad Al Masarihah', 'name' => 'أحد المسارحة' ],
        ['en_name' => 'Al Edabi', 'name' => 'العيدابي' ],
        ['en_name' => 'Fayfa', 'name' => 'فيفاء' ],
        ['en_name' => 'Al Tuwal', 'name' => 'الطوال' ],
        ['en_name' => 'Fugitive', 'name' => 'هروب' ],
        ['en_name' => 'Najran', 'name' => 'نجران' ],
        ['en_name' => 'Sharorah', 'name' => 'شرورة' ],
        ['en_name' => 'Hubuna', 'name' => 'حبونا' ],
        ['en_name' => 'Badr Al Janoub', 'name' => 'بدر الجنوب' ],
        ['en_name' => 'Yadamah', 'name' => 'يدمه' ],
        ['en_name' => 'Thar', 'name' => 'ثار' ],
        ['en_name' => 'Khbash', 'name' => 'خباش' ],
        ['en_name' => 'Al Kharkhir', 'name' => 'الخرخير' ],
        ['en_name' => 'Al Bahah', 'name' => 'الباحة' ],
        ['en_name' => 'Baljurashi', 'name' => 'بلجرشي' ],
        ['en_name' => 'Al Mandaq', 'name' => 'المندق' ],
        ['en_name' => 'Al Makhwah', 'name' => 'المخواة' ],
        ['en_name' => 'Qilwah', 'name' => 'قلوة' ],
        ['en_name' => 'Al Aqiq', 'name' => 'العقيق' ],
        ['en_name' => 'Al Qara', 'name' => 'القرى' ],
        ['en_name' => 'Ghamed Al-Zinad', 'name' => 'غامد الزناد' ],
        ['en_name' => 'Hajrah', 'name' => 'الحجرة' ],
        ['en_name' => 'Bani Hasan', 'name' => 'بني حسن' ],
        ['en_name' => 'Sakakah', 'name' => 'سكاكا' ],
        ['en_name' => 'Al Qurayyat', 'name' => 'القريات' ],
        ['en_name' => 'Dumat Al-Jandal', 'name' => 'دومة الجندل' ],
        ['en_name' => 'Tabarjal', 'name' => 'طبرجل' ],
    ];
